#!/bin/bash
#PBS -S /bin/bash
#PBS -o /home/vla/python/bitc_Mg/Mg2EDTA/2.bitc_numpyro_lognomP0_lognomLs/repeat_2/numpyro.log 
#PBS -j oe
#PBS -l nodes=1:ppn=1,mem=2048mb,walltime=72:00:00

module load miniconda/3
source activate bitc
cd /home/vla/python/bitc_Mg/Mg2EDTA/2.bitc_numpyro_lognomP0_lognomLs/repeat_2
date
python /home/vla/python/bitc_Mg/scripts/run_numpyro.py --itc_data_dir /home/vla/python/bitc_Mg/Mg2EDTA/1.itc_origin_heat_files --heat_data_dir /home/vla/python/bitc_Mg/Mg2EDTA/1.itc_origin_heat_files --experimental_design_parameters_dir /home/vla/python/bitc_Mg/Mg2EDTA/1.experimental_information --experiments "Mg1EDTAp1a Mg1EDTAp1b Mg1EDTAp1c Mg1EDTAp1d Mg1EDTAp1e Mgp5EDTAp05a Mgp5EDTAp05b Mgp5EDTAp05c Mgp5EDTAp05e Mgp5EDTAp05f Mgp5EDTAp05g Mgp5EDTAp05h Mgp5EDTAp05i Mgp5EDTAp05j"  --dc 0.100000  --ds 0.100000     --concentration_range_factor 10.000000  --niters 100000  --nburn 10000  --nthin 10  --nchain 4  --random_key 2 
date 
